apiVersion: v1
kind: Pod
metadata:
  name: my-web-server-env
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    env:
    - name: MY_ENV_VAR
      value: "my-value"

