# Default values for helm_project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

containers:
  image: nginx:latest

service:
  type: NodePort
  port: 80
  
pv:
  storage: 1Gi
  path: "/mnt/data"
